name: Release

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string

jobs:
  setup:
    if: >-
      !github.event.inputs.version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_lookup.outputs.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lookup current version
      id: version_lookup
      run: |
        VERSION=$(git tag --points-at)
        echo "::set-output name=version::$VERSION"
        echo "$VERSION"

  build:
    needs: [setup]
    if: >-
      !failure() &&
      !github.event.inputs.version &&
      !needs.setup.outputs.version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup ruby
      uses: ruby/setup-ruby@v1

    - name: Create artifact
      run: |
        _internals/shell-functions/create-artifact.sh

    - name: Publish release
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx semantic-release
        VERSION=$(git tag --points-at)
        echo "::set-output name=version::$VERSION"

  preview:
    needs: [setup, build]
    if: >-
      !failure() && (
        github.event.inputs.version || 
        needs.setup.outputs.version ||
        needs.build.outputs.version
      )
    uses: ./.github/workflows/cdk-deploy.yml
    with:
      version: >-
        ${{
          github.event.inputs.version || 
          needs.setup.outputs.version ||
          needs.build.outputs.version
        }}
      awsRegion: us-east-2
      environment: Preview
      context: >-
        _internals/site-contexts/_common.json
        _internals/site-contexts/env-preview.json
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  production:
    needs: [setup, build, preview]
    if: >-
      !failure() && (
        github.event.inputs.version || 
        needs.setup.outputs.version ||
        needs.build.outputs.version
      )
    uses: ./.github/workflows/cdk-deploy.yml
    with:
      version: >-
        ${{
          github.event.inputs.version || 
          needs.setup.outputs.version ||
          needs.build.outputs.version
        }}
      awsRegion: us-east-2
      environment: Production
      context: >-
        _internals/site-contexts/_common.json
        _internals/site-contexts/env-production.json
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
