name: Release

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches: [master]
    
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string

jobs:
  setup:
    if: >-
      !github.event.inputs.version &&
      !github.event.pull_request
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_lookup.outputs.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Lookup current version
      id: version_lookup
      run: |
        VERSION=$(git tag --points-at)
        echo "::set-output name=version::$VERSION"
        echo "$VERSION"

  build:
    needs: [setup]
    if: >-
      !failure() &&
      !github.event.inputs.version &&
      !needs.setup.outputs.version
    runs-on: ubuntu-latest
    outputs:
      artifactBaseName: ${{ steps.artifact_path.outputs.artifact_basename }}
      artifactDirName: ${{ steps.artifact_path.outputs.artifact_dirname }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup ruby
      uses: ruby/setup-ruby@v1

    - name: Create artifact
      run: |
        _internals/shell-functions/create-artifact.sh

    - name: Get artifact defaults
      id: artifact_path
      run: |
        source _internals/defaults.sh
        echo "::set-output name=artifact_basename::$(basename "$ARTIFACT_PATH" .zip)"
        echo "::set-output name=artifact_dirname::$(dirname "$ARTIFACT_PATH")"

    - name: Upload release candidate
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.artifact_path.outputs.artifact_basename }}
        path: ${{ steps.artifact_path.outputs.artifact_dirname }}

  integration_up:
    needs: [setup, build]
    if: >-
      !failure() &&
      !github.event.inputs.version &&
      !needs.setup.outputs.version
    uses: kevjallen/static-site/.github/workflows/stack-up.yml@master
    with:
      environment: Integration
      context: >-
        _internals/site-contexts/_common.json
        _internals/site-contexts/env-integration.json
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      awsRegion: ${{ secrets.AWS_DEFAULT_REGION }}   

  integration_down:
    needs: [setup, build, integration_up]
    if: >-
      !failure()
    uses: kevjallen/static-site/.github/workflows/stack-down.yml@master
    with: 
      environment: Integration
      context: >-
        _internals/site-contexts/_common.json
        _internals/site-contexts/env-integration.json
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      awsRegion: ${{ secrets.AWS_DEFAULT_REGION }}          
    

  release:
    needs: [setup, build, integration_up]
    if: >-
      !failure() &&
      !github.event.inputs.version &&
      !needs.setup.outputs.version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }} 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download release candidate
      uses: actions/download-artifact@v2
      with:
        name: ${{ needs.build.outputs.artifactBaseName }}
        path: ${{ needs.build.outputs.artifactDirName }}

    - name: Create official release
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx semantic-release
        VERSION=$(git tag --points-at)
        echo "::set-output name=version::$VERSION"

  preview:
    needs: [setup, build, integration_up, release]
    if: >-
      !failure() && (
        github.event.inputs.version ||
        needs.setup.outputs.version ||
        needs.release.outputs.version
      )
    uses: kevjallen/static-site/.github/workflows/stack-up.yml@master
    with:
      version: >-
        ${{
          github.event.inputs.version ||
          needs.setup.outputs.version ||
          needs.release.outputs.version
        }}
      environment: Preview
      context: >-
        _internals/site-contexts/_common.json
        _internals/site-contexts/env-preview.json
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      awsRegion: ${{ secrets.AWS_DEFAULT_REGION }}

  production:
    needs: [setup, build, integration_up, release, preview]
    if: >-
      !failure() && (
        github.event.inputs.version ||
        needs.setup.outputs.version ||
        needs.release.outputs.version
      )
    uses: kevjallen/static-site/.github/workflows/stack-up.yml@master
    with:
      version: >-
        ${{
          github.event.inputs.version ||
          needs.setup.outputs.version ||
          needs.release.outputs.version
        }}
      environment: Production
      context: >-
        _internals/site-contexts/_common.json
        _internals/site-contexts/env-production.json
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      awsRegion: ${{ secrets.AWS_DEFAULT_REGION }}
