name: Release

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
    inputs:
      environment:
        default: All
        options:
        - All
        - Preview
        - Production
        required: true
        type: choice
      artifactName:
        required: false
        type: string
      artifactRun:
        required: false
        type: string

jobs:
  build:
    if: ${{ github.event.inputs.artifactRun == '' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup ruby
      uses: ruby/setup-ruby@v1

    - name: Create artifact
      run: |
        _internals/shell-functions/create-artifact.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: _artifact/site.zip

  dummy:
    needs: [build]
    if: |
      !failure() &&
      github.event.inputs.environment == '' ||
      github.event.inputs.environment == 'All' ||
      github.event.inputs.environment == 'Dummy'
    uses: ./.github/workflows/cdk-deploy.yml
    with:
      artifactName: ${{ github.event.inputs.artifactName || 'site' }}
      artifactRun: ${{ github.event.inputs.artifactRun }}
      awsRegion: us-east-2
      environment: Dummy
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  preview:
    needs: [build, dummy]
    if: |
      !failure() &&
      github.event.inputs.environment == '' ||
      github.event.inputs.environment == 'All' ||
      github.event.inputs.environment == 'Preview'
    uses: ./.github/workflows/cdk-deploy.yml
    with:
      artifactName: ${{ github.event.inputs.artifactName || 'site' }}
      artifactRun: ${{ github.event.inputs.artifactRun }}
      awsRegion: us-east-2
      environment: Preview
      context: >
        _internals/site-contexts/_common.json
        _internals/site-contexts/env-preview.json
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  production:
    needs: [build, dummy, preview]
    if: |
      !failure() &&
      github.event.inputs.environment == '' ||
      github.event.inputs.environment == 'All' ||
      github.event.inputs.environment == 'Production'
    uses: ./.github/workflows/cdk-deploy.yml
    with:
      artifactName: ${{ github.event.inputs.artifactName || 'site' }}
      artifactRun: ${{ github.event.inputs.artifactRun }}
      awsRegion: us-east-2
      environment: Production
      context: >
        _internals/site-contexts/_common.json
        _internals/site-contexts/env-production.json
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      githubToken: ${{ secrets.GITHUB_TOKEN }}
