name: Release

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
    inputs:
      environment:
        default: All
        options:
        - All
        - Preview
        - Production
        required: true
        type: choice
      version:
        required: false
        type: string

jobs:
  build:
    if: ${{ github.event.inputs.version == '' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup ruby
      uses: ruby/setup-ruby@v1

    - name: Setup asdf
      uses: asdf-vm/actions/setup@v1

    - name: Install nodejs
      run: |
        asdf plugin add nodejs && asdf install nodejs

    - name: Create artifact
      run: |
        _internals/shell-functions/create-artifact.sh

    - name: Publish release
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx semantic-release
        VERSION=$(git tag --points-at) || return 0
        echo "::set-output name=version::$VERSION"

  preview:
    needs: [build]
    if: |
      !failure() && (github.event.inputs.environment || needs.build.outputs.version) &&
      github.event.inputs.environment == '' ||
      github.event.inputs.environment == 'All' ||
      github.event.inputs.environment == 'Preview'
    uses: ./.github/workflows/cdk-deploy.yml
    with:
      version: ${{ github.event.inputs.environment || needs.build.outputs.version }}
      awsRegion: us-east-2
      environment: Preview
      context: >
        _internals/site-contexts/_common.json
        _internals/site-contexts/env-preview.json
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  production:
    needs: [build, preview]
    if: |
      !failure() && (github.event.inputs.environment || needs.build.outputs.version) &&
      github.event.inputs.environment == '' ||
      github.event.inputs.environment == 'All' ||
      github.event.inputs.environment == 'Production'
    uses: ./.github/workflows/cdk-deploy.yml
    with:
      version: ${{ github.event.inputs.environment || needs.build.outputs.version }}
      awsRegion: us-east-2
      environment: Production
      context: >
        _internals/site-contexts/_common.json
        _internals/site-contexts/env-production.json
    secrets:
      awsAccountId: ${{ secrets.AWS_ACCOUNT_ID }}
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
