name: Inspect stack

on:
  workflow_call:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get defaults
      id: defaults
      run: |
        source _internals/defaults.sh
        echo "::set-output name=stack_path::$AWS_STACK_PATH"

    - name: Run linter
      env:
        AWS_STACK_PATH: ${{ steps.defaults.outputs.stack_path }}
      run: |
        cd "$AWS_STACK_PATH"
        npm install && npm run lint
