name: Destroy stack

on:
  workflow_call:

    inputs:
      environment:
        required: true
        type: string
      contextFiles:
        type: string
      cdkArguments:
        type: string

    secrets:
      awsAccountId:
        required: true
      awsRegion:
        required: true
      awsAccessKeyId:
        required: true
      awsSecretAccessKey:
        required: true

jobs:
  clean_up:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup asdf
      uses: asdf-vm/actions/setup@v1

    - name: Install nodejs
      run: |
        asdf plugin add nodejs && asdf install nodejs

    - name: Install jq
      run: |
        asdf plugin add jq && asdf install jq

    - name: Read CDK context
      id: cdk_context
      if: ${{ inputs.contextFiles }}
      env:
        CONTEXT_FILES: ${{ inputs.contextFiles }}
      run: |
        CDK_CONTEXT_ARGS=$(_internals/shell-functions/context-args-from.sh \
          $CONTEXT_FILES)
        echo "::set-output name=cdk_context_args::$CDK_CONTEXT_ARGS"

    - name: Destroy environment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.awsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.awsSecretAccessKey }}
        AWS_ACCOUNT_ID: ${{ secrets.awsAccountId }}
        AWS_REGION: ${{ secrets.awsRegion }}
        CDK_CONTEXT_ARGS: ${{ steps.cdk_context.outputs.cdk_context_args }}
        CDK_USER_ARGS: ${{ inputs.cdkArguments }}
      run: |
        _internals/shell-functions/npm-run-cdk.sh 'destroy' \
          "$AWS_ACCOUNT_ID" "$AWS_REGION" $CDK_CONTEXT_ARGS $CDK_USER_ARGS
