name: Apply stack

on:
  workflow_call:

    inputs:
      environment:
        required: true
        type: string
      version:
        type: string
      contextFiles:
        type: string
      cdkArguments:
        type: string

    secrets:
      awsAccountId:
        required: true
      awsRegion:
        required: true
      awsAccessKeyId:
        required: true
      awsSecretAccessKey:
        required: true

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      ref: ${{ inputs.version }}

    - name: Setup asdf
      uses: asdf-vm/actions/setup@v1

    - name: Install jq
      run: |
        asdf plugin add jq && asdf install jq

    - name: Install nodejs
      run: |
        asdf plugin add nodejs && asdf install nodejs

    - name: Get artifact defaults
      id: defaults
      run: |
        source _internals/defaults.sh
        echo "::set-output name=artifact_name::$(basename "$ARTIFACT_PATH" .zip)"
        echo "::set-output name=artifact_dirname::$(dirname "$ARTIFACT_PATH")"
        echo "::set-output name=artifact_basename::$(basename "$ARTIFACT_PATH")"

    - name: Download release candidate
      if: ${{ !inputs.version }}
      uses: actions/download-artifact@v2
      with:
        name: ${{ steps.defaults.outputs.artifact_name }}
        path: ${{ steps.defaults.outputs.artifact_dirname }}

    - name: Download official release
      if: ${{ inputs.version }}
      env: 
        ARTIFACT_BASENAME: ${{ steps.defaults.outputs.artifact_basename }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        VERSION: ${{ inputs.version }}
      run: |
        _internals/shell-functions/download-release.sh \
          "$GITHUB_REPOSITORY" "$VERSION" "$ARTIFACT_BASENAME"

    - name: Read CDK context
      if: ${{ inputs.contextFiles }}
      id: cdk_context
      env:
        CONTEXT_FILES: ${{ inputs.contextFiles }}
      run: |
        CDK_CONTEXT_ARGS=$(_internals/shell-functions/context-args-from.sh \
          $CONTEXT_FILES)
        echo "::set-output name=cdk_context_args::$CDK_CONTEXT_ARGS"

    - name: Synth environment
      id: cdk_synth
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.awsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.awsSecretAccessKey }}
        AWS_ACCOUNT_ID: ${{ secrets.awsAccountId }}
        AWS_REGION: ${{ secrets.awsRegion }}
        CDK_CONTEXT_ARGS: ${{ steps.cdk_context.outputs.cdk_context_args }}
        CDK_USER_ARGS: ${{ inputs.cdkArguments }} 
      run: |
        TEMPLATE=$(_internals/shell-functions/npm-run-cdk.sh 'synth' \
          "$AWS_ACCOUNT_ID" "$AWS_REGION" $CDK_CONTEXT_ARGS $CDK_USER_ARGS)
        echo "::set-output name=template::$(echo "$TEMPLATE" | jq -c)"

    - name: Deploy environment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.awsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.awsSecretAccessKey }}
        AWS_ACCOUNT_ID: ${{ secrets.awsAccountId }}
        AWS_REGION: ${{ secrets.awsRegion }}
        CDK_CONTEXT_ARGS: ${{ steps.cdk_context.outputs.cdk_context_args }} 
        CDK_USER_ARGS: ${{ inputs.cdkArguments }}
      run: |
        _internals/shell-functions/npm-run-cdk.sh 'deploy' \
          "$AWS_ACCOUNT_ID" "$AWS_REGION" $CDK_CONTEXT_ARGS $CDK_USER_ARGS

    - name: Run E2E tests
      env:
        TEMPLATE: ${{ steps.cdk_synth.outputs.template }}
      run: |
        _internals/shell-functions/run-e2e-tests-with.sh "$TEMPLATE"
